const log = [
	{
		"version": "v1.3.0",
		"pr": "https://github.com/TurboWarp/extensions/pull/2562",
		"js": "https://github.com/TurboWarp/extensions/blob/66755ce587c7c200eb60e0d0c4bd16d401f91724/extensions/Xeltalliv/simple3D.js",
		"changes": [
			"Added (texture from video [NAME]) block, which allows projects to upload current frame of the video from Lily/Video extension into the texture",
			"Added [set [NAME] vertex draw ranges from [STARTS] to [ENDS]] block, which allows setting multiple draw ranges at once. This allows toggling drawing of different sections of a mesh independently in one draw call, which can be useful for culling",
			"Added [set [NAME] primitive size [SIZE]] block for setting size of point primitives or width of line primitives",
			"Added 'primitive size' option for (mesh [NAME] [PROP]) block",
			"Added [skew [AXIS1] by [FACTOR] [AXIS2]] block",
			"Renamed [render to stage] block into [render to canvas]",
			"Added [when stage resolution changes] block",
			"Added (stage width) and (stage height) blocks",
			"Added (horizontal stage resolution) and (vertical stage resolution) blocks",
			"Added <high quality pen enabled?> block",
			"Added [set canvas [SIZE] to X: [X] Y: [Y]] and [clear canvas [SIZE]] blocks",
			"Added [make scaled canvas look [FILTER]] block",
			"Renamed [when resolution changes] block into [when canvas resolution changed]",
			"Renamed [stage width] block into [canvas width]",
			"Renamed [stage height] block into [canvas height]",
			"Added [display canvas on myself] and [retore my look] blocks",
			"Added [set Simple3D layer visibility to [STATE]] block",
			"Added [reset everything with antialiasing [ANTIALIAS]] block",
			"Removed broken transform caching introduced in v1.2.2",
			"Fixed bug where [set [NAME] [TRANSFORMS] transforms [MATRIXES]] block called on a mesh that doesn't exist was causing an exception to be thrown",
			"Fixes bug where clipping areas weren't getting reset, when calling [reset everything] block or importing another project.",
			"Gave canvas id 'simple3d-canvas' to make it easier to find when using Spector.js",
			"Added line numbers to error message when shaders fail to compile",
			"Accessing i_will_not_ask_for_help_when_these_break now asks to import Simple3D from text, to prevent other extensions within the project from breaking, whenever Simple3D update changes its internal structure",
		],
	},
	{
		"version": "v1.2.2",
		"pr": "https://github.com/TurboWarp/extensions/pull/2085",
		"js": "https://raw.githubusercontent.com/TurboWarp/extensions/fca86f3452529fc516ea8711c299bdbe6f7ea7ed/extensions/Xeltalliv/simple3D.js",
		"changes": [
			"Fixed detection of Simple3D layer by touching blocks",
			"Optimized textures from lists",
			"Optimized transform direction block",
			"Added caching to transform from-to blocks (EDIT: this partially broke those blocks, fixed in v1.3.0)",
		],
	},
	{
		"version": "v1.2.1",
		"pr": "https://github.com/TurboWarp/extensions/pull/1788",
		"js": "https://raw.githubusercontent.com/TurboWarp/extensions/0ccb518f535fc2cf5cba9d87affcac54ad75e0cb/extensions/Xeltalliv/simple3D.js",
		"changes": [
			"Fixed reading render target to list and to dataURI not working unless the reading area was set",
		],
	},
	{
		"version": "v1.2.0",
		"pr": "https://github.com/TurboWarp/extensions/pull/1738",
		"js": "https://raw.githubusercontent.com/TurboWarp/extensions/2e9eb5af777b15e3b7b698a38e566f57791f47ff/extensions/Xeltalliv/simple3D.js",
		"changes": [
			"Changed the way bone transforms block handles cases of missing original transforms or mismatching data",
			"Changed bone transforms to be inheritable",
			"Added [set [NAME] instance draw limit []] block for limiting amount of drawn instances",
			"Added [set [BOXTYPE] X1:[] Y1:[] X2:[] Y2:[]] and [clear [BOXTYPE]] blocks for specifying and clearing viewport, clipping and pixel readback boxes",
			"Added 3 new options into mesh property reported for estimating VRAM usage",
			"Added a link to the tutorial in the documentation",
			"Added a warning for exceeding vertex index limit",
			"Added a 90 second limit for model decoder. After that, it gets restarted",
			"Added clearing of all the model importing queue upon the call to [reset everything]",
			"Added temporary unstable exports to the external API",
			"Optimized transforms",
			"Optimized extension for cases when it's sitting idle and isn't used",
		],
	},
	{
		"version": "v1.1.0",
		"pr": "https://github.com/TurboWarp/extensions/pull/1618",
		"js": "https://raw.githubusercontent.com/TurboWarp/extensions/8f48237a8a90a3e763b0291f6be775f59f689bd6/extensions/Xeltalliv/simple3D.js",
		"changes": [
			"Deprecated and hidden [set [NAME] accurate interpolation [STATE]] block",
			"Added [set [NAME] compute color [MODE]] block instead of it, which has 1 extra mode",
			"Added [set [NAME] interleaved [PROPERTY] [LIST]] for setting mesh properties from a single list",
			"Added new blending mode \"default behind\", which draws new primitives behind of what is already drawn",
			"Added ability to measure text's horizontal advance distance, which is different from text's bounding box width",
			"Added support for properly removing extension in PenguinMod, Snail IDE and other mods",
			"Added support for SharkPool's \"Layer Control\" extension",
			"Fixed [set clear color R:[] G:[] B:[] A:[]] block to take into a count premultiplied alpha",
			"Fixed bug were it would always use accurate interpolating for vertex colors regardless of what was set",
			"When drawing text with border, the border now extends the image by exactly ceiling of specified size in each of 4 directions",
			"Changed default value of near plane from 0.01 to 0.1 to significantly reduce Z-fighting",
			"Clarified which parts of the code are MPL-2.0 and which are BSD-3-Clause",
		],
	},
	{
		"version": "v1.0.4",
		"pr": "https://github.com/TurboWarp/extensions/pull/1593",
		"js": "https://raw.githubusercontent.com/TurboWarp/extensions/034d737a80eacd78c124a974e7807b34f9093a5a/extensions/Xeltalliv/simple3D.js",
		"changes": [
			"Added \"Open extra resources\" button",
			"Added 2 new comments to sample project",
		],
	},
	{
		"version": "v1.0.3",
		"pr": "https://github.com/TurboWarp/extensions/pull/1500",
		"js": "https://raw.githubusercontent.com/TurboWarp/extensions/6d972537a86165d2515c2167e5a5c2974afa1406/extensions/Xeltalliv/simple3D.js",
		"changes": [
			"Fixed [set [NAME] vertex draw range from (FROM) to (TO)] block",
			"Added popup when extension is packaged incorrectly",
			"Fixed instance XY positions",
			"Fixed font block incorrect ArgumentType",
			"Added extra costume with UV to sample project",
			"Improved docs",
		],
	},
	{
		"version": "v1.0.2",
		"pr": "https://github.com/TurboWarp/extensions/pull/1480",
		"js": "https://raw.githubusercontent.com/TurboWarp/extensions/07ba2912ed0f105aef9cedc75ee7efd8858007e4/extensions/Xeltalliv/simple3D.js",
		"changes": [
			"Fixed [transform direction X: [X] Y: [Y] Z: [Z] from [FROM] to [TO]] block corrupting tranformations that it was only meant to read",
			"Fixed meshes without vertex positions attached causing a crash",
			"Added missing \"?? 1\" in Off file importer",
			"Fixed reading material diffuse colors in Obj importer",
			"Fixed \"importing from file\" transform deforming meshes",
			"Improved Off importer to better comply with specification",
		],
	},
	{
		"version": "v1.0.1",
		"pr": "https://github.com/TurboWarp/extensions/pull/1468",
		"js": "https://raw.githubusercontent.com/TurboWarp/extensions/b8abfd0494beff6b992c731affdb91750e7608ad/extensions/Xeltalliv/simple3D.js",
		"changes": [
			"Fixed [reset transformation's [COMPONENT]] block in PenguinMod",
			"Fixed \"projected (scratch units)\" in [transform X: [X] Y: [Y] Z: [Z] from [FROM] to [TO]] block",
			"Improved docs",
		],
	},
	{
		"version": "v1.0.0",
		"pr": "https://github.com/TurboWarp/extensions/pull/1417",
		"js": "https://raw.githubusercontent.com/TurboWarp/extensions/cb6ec3e7baae6370f0c3a90df1235ca36ee91369/extensions/Xeltalliv/simple3D.js",
		"changes": [
			"Initial release"
		],
	},
];
